### ISSUE TITLE
One problem is about data interception 

### ISSUE THREAD

**Issue by Lizhanying-Sudo** [dalinzhangzdl/BCI_MI_Wavelet_CNN#2]
你好，zhang同学：

在使用您的代码进行小波变换时，有个小疑问不太明白，您的代码如下，为何您这里截取7到30 个点进行合并。

`cwtmatr = np.concatenate([abs(cwtmatr3[7:30,:]), abs(cwtmatr4[7:30,:])],axis=0)`

非常希望您能得空解答我的疑惑，先谢谢您啦！

**Comment by dalinzhangzdl** [comment]
7到30表示mu/beta频段

**Comment by Lizhanying-Sudo** [comment]
明白啦。非常感谢
